// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEqr7pl2igz1TmjLOWQPYXhzCS-KoPzg8',
    appId: '1:549682836299:web:5109dc3c29881a25db6ece',
    messagingSenderId: '549682836299',
    projectId: 'lufthansa-9ef97',
    authDomain: 'lufthansa-9ef97.firebaseapp.com',
    storageBucket: 'lufthansa-9ef97.appspot.com',
    measurementId: 'G-BVCN3LZ835',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSnwVGs8XGkEyExdmE3iCSQWGJb_S6PVs',
    appId: '1:549682836299:android:cddd6a7ced99afb3db6ece',
    messagingSenderId: '549682836299',
    projectId: 'lufthansa-9ef97',
    storageBucket: 'lufthansa-9ef97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ2RI1kwsMc4F0BmQ4npxkmpbAGX0w6cE',
    appId: '1:549682836299:ios:1875800776d12ad1db6ece',
    messagingSenderId: '549682836299',
    projectId: 'lufthansa-9ef97',
    storageBucket: 'lufthansa-9ef97.appspot.com',
    iosClientId: '549682836299-53l9ebcqj26ibopnogq536sp64ne3i3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.lufthansa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQ2RI1kwsMc4F0BmQ4npxkmpbAGX0w6cE',
    appId: '1:549682836299:ios:1875800776d12ad1db6ece',
    messagingSenderId: '549682836299',
    projectId: 'lufthansa-9ef97',
    storageBucket: 'lufthansa-9ef97.appspot.com',
    iosClientId: '549682836299-53l9ebcqj26ibopnogq536sp64ne3i3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.lufthansa',
  );
}
